add markup section Advantages
margarytak/KoRovKaTeamProject pull request #7
Opened 2022-05-07 20:27 UTC by Tasha51

Додано розмітку секції Advantages і мінімальний CSS без картинок

2022-05-07 21:15 UTC, margarytak requested changes

2022-05-07 21:15 UTC, margarytak commented on src/sass/components/_advantages.scss
> +        padding-bottom: 80px;
pt 20px, 
pb 40 -> уже есть в общих стилях

можно и без $.section а просто на advantages - перебьет спокойно

2022-05-07 21:15 UTC, margarytak commented on src/sass/components/_advantages.scss
> +    margin-bottom: 16px;
на таблетке будет mb-13px. Давай и тут поставим 13 а для десктопа уже будет 16px?

2022-05-07 21:15 UTC, margarytak commented on src/sass/components/_advantages.scss
> +    margin-right: 70px;
вместо дикого марджина лучше поставить ширину элементу   max-width: 230px;

2022-05-08 07:19 UTC, Tasha51 commented on src/sass/components/_advantages.scss
> +        padding-bottom: 80px;
Перекинула на advantages

2022-05-08 07:20 UTC, Tasha51 commented on src/sass/components/_advantages.scss
> +    margin-bottom: 16px;
Там трішки кривенький макет, довго думала який маржин ставити. Змінила

2022-05-08 07:21 UTC, Tasha51 commented on src/sass/components/_advantages.scss
> +    margin-right: 70px;
Твоя рація! Переробила

2022-05-08 08:51 UTC, margarytak approved these changes

2022-05-08 08:52 UTC, merged